name: CI

on:
  push:
    branches:
      - develop
      - main
      - feature/welcome-message-8
  pull_request:
    branches:
      - develop
      - main
      - feature/welcome-message-8

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}  
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PREMIER_CHANNEL_ID: ${{ secrets.PREMIER_CHANNEL_ID }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      ROLE_ID: ${{ secrets.ROLE_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        PYTHONPATH=./ pytest tests/